ha_version: "stable"
ha_version_override: ""

ha_config_repo: "https://github.com/{{ lookup('env','GITHUB_USERNAME') }}/homelab-config.git"
ha_config_repo_branch: "main"
ha_config_repo_subdir: "homeassistant"

github_username: "{{ lookup('env','GITHUB_USERNAME') }}"
github_pat: "{{ lookup('env','GITHUB_PAT') }}"

cf_tunnel_id: "{{ lookup('env','CF_TUNNEL_ID') }}"
cf_hostname: "{{ lookup('env','CF_HOSTNAME') }}"
cf_creds_src: "{{ lookup('env','CF_CREDS_SRC') }}"
