---
- name: restart wireguard
  ansible.builtin.systemd:
    name: "wg-quick@{{ nanopirouter_wg_interface }}"
    state: restarted

- name: Restart avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon
    state: restarted
