---
- name: Install router utility packages
  ansible.builtin.apt:
    name:
      - bind9-dnsutils
    state: present
    update_cache: false

- name: Allow unprivileged users to use ping
  ansible.builtin.sysctl:
    name: net.ipv4.ping_group_range
    value: "0 2147483647"
    sysctl_set: true
    reload: true
