- name: Install Docker engine
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Enable & start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
